[package]
name = "yarms-security"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "security"
path = "src/lib.rs"

[dependencies]
rand_core = { version = "0.6", features = ["std"] }
pbkdf2 = "0.11.0"
anyhow = "1.0.58"
thiserror = "1.0.31"
